version: '3.8'

services:
  resourcespace:
    image: ${RESOURCESPACE_IMAGE}
    volumes:
      - ./resourcespace/config.php:/var/www/html/include/config.php
      - ./resourcespace/filestore:/var/www/html/filestore
      # Add plugins here
      # - ./my-plugin:/var/www/html/plugins/my-plugin
    networks:
      - resourcespace-network

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - resourcespace-network

networks:
  resourcespace-network:
    driver: bridge

volumes:
  mariadb-data:
  resourcespace-data: